#!/bin/bash

export GAME_ROOT="$(dirname "$0")"

load_player_data(){
    source "$GAME_ROOT/data/player_data.sh"
}

save_player_data() {
    cat > "$GAME_ROOT/data/player_data.sh" << EOF
#!/bin/bash
 
PLAYER_NAME="$PLAYER_NAME"
PLAYER_LEVEL=$PLAYER_LEVEL
PLAYER_XP=$PLAYER_XP
PLAYER_XP_NEXT=$PLAYER_XP_NEXT
PLAYER_GOLD=$PLAYER_GOLD
PLAYER_FLOOR=$PLAYER_FLOOR
 
PLAYER_HP=$PLAYER_HP
PLAYER_HP_MAX=$PLAYER_HP_MAX
PLAYER_ATK=$PLAYER_ATK
PLAYER_DEF=$PLAYER_DEF
PLAYER_NRG=$PLAYER_NRG
PLAYER_NRG_MAX=$PLAYER_NRG_MAX
PLAYER_SPD=$PLAYER_SPD
PLAYER_LCK=$PLAYER_LCK
 
PLAYER_WEAPON="$PLAYER_WEAPON"
PLAYER_ARMOR="$PLAYER_ARMOR"
PLAYER_HAT="$PLAYER_HAT"
 
PLAYER_ITEMS="$PLAYER_ITEMS"
PLAYER_SKILL_CARDS="$PLAYER_SKILL_CARDS"
EOF
}